Develop
amcspps/daemon pull request #1
Opened 2023-10-29 23:42 UTC by amcspps

2023-10-30 14:17 UTC, DariaWelt requested changes
Моим gcc не компилируется:
```
root@Ubuntu:/home/vboxuser/os_labs/pavel_popov_amcspps# ./build.sh 
-- The C compiler identification is GNU 11.4.0
-- The CXX compiler identification is GNU 11.4.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Configuring done
-- Generating done
-- Build files have been written to: /home/vboxuser/os_labs/pavel_popov_amcspps
[ 33%] Building CXX object CMakeFiles/daemon.dir/main.cpp.o
[ 66%] Building CXX object CMakeFiles/daemon.dir/daemon.cpp.o
/home/vboxuser/os_labs/pavel_popov_amcspps/daemon.cpp:10:10: fatal error: format: No such file or directory
   10 | #include <format>
      |          ^~~~~~~~
compilation terminated.
make[2]: *** [CMakeFiles/daemon.dir/build.make:90: CMakeFiles/daemon.dir/daemon.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:83: CMakeFiles/daemon.dir/all] Error 2
make: *** [Makefile:91: all] Error 2
now start daemon using following instruction:
->sudo ./daemon </path/to/config>
->cfg path for test example is ./cfg.txt
root@Ubuntu:/home/vboxuser/os_labs/pavel_popov_amcspps# gcc --version
gcc (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0
Copyright (C) 2021 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

2023-10-30 14:17 UTC, DariaWelt commented on daemon.cpp
> +	if(fork()) {
Форк может окончится ошибкой

2023-11-03 15:53 UTC, amcspps commented on daemon.cpp
> +	if(fork()) {
1) переписал без 20 стандарта, теперь должно скомпилиться без проблем.
2) поправил

2023-11-05 09:12 UTC, DariaWelt approved these changes
Работа зачтена.

2023-11-05 09:12 UTC, merged